version: '3.1'
services:
  website:
    image: php:8.0-apache
    volumes:
      - ./website:/var/www/html
    depends_on:
      - API
    ports:
      - "8080:80"
    networks:
      - kkaj
    environment:
      - USERNAME=toto
      - PASSWORD=python
  API:
    image: simple-api:1
    networks:
      - kkaj
    restart: "always"
 
networks:
  kkaj:
